import { useState } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { useCVScanner } from '@/hooks/useCVScanner';
import { Button } from '@/components/ui/button';
import { UploadCloud, FileText, Crosshair, Download } from 'lucide-react';
import { toast } from 'sonner';
import { checkAndUnlockAchievements } from '@/services/gameService';

export function CvAtsChecker() {
  const { user } = useAuth();
  const { isScanning, uploadProgress, scanResume, scanResult } = useCVScanner(user?.id);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      if (file.size > 5 * 1024 * 1024) {
        toast.error('File terlalu besar! Maksimal 5MB.');
        return;
      }
      setSelectedFile(file);
    }
  };

  const handleScan = async () => {
    if (!selectedFile) {
      toast.error('Pilih file dulu!');
      return;
    }
    await scanResume(selectedFile);
    if (user?.id) {
      await checkAndUnlockAchievements(user.id);
    }
    setSelectedFile(null);
  };

  const downloadReport = () => {
    if (!scanResult) return;
    const content = `
========================================
  ATS RESUME SCAN REPORT
========================================

File: ${scanResult.fileName}
Score: ${scanResult.score}/100

--- FEEDBACK & IMPROVEMENT SUGGESTIONS ---

${scanResult.feedback.map((item, i) => `${i+1}. ${item}`).join('\n')}

========================================
  Generated by AI-TOOLKIT
========================================
`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ATS_Report_${new Date().toISOString().slice(0,10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-8 duration-700 w-full">
      {/* HEADER PIXEL */}
      <div className="space-y-2">
        <h2 className="text-3xl font-pixel text-white tracking-widest flex items-center gap-3">
          <Crosshair className="text-pink-500 w-8 h-8" />
          <span className="bg-gradient-to-r from-pink-500 to-violet-500 bg-clip-text text-transparent">ATS</span>
          <span className="text-white">RESUME SCANNER</span>
        </h2>
        <p className="text-zinc-400 font-pixel text-xs tracking-widest uppercase">Upload CV-mu, AI akan menganalisis dan memberi skor ATS.</p>
      </div>

      {/* UPLOAD AREA - PIXEL STYLE */}
      <div className="game-panel border-2 border-dashed border-violet-500/30 hover:border-pink-500/50 rounded-3xl p-12 flex flex-col items-center justify-center text-center transition-all duration-300 group relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-t from-pink-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none"></div>

        {!isScanning ? (
          <>
            <div className="bg-white/5 p-4 rounded-full mb-6 group-hover:scale-110 transition-transform shadow-[0_0_20px_rgba(139,92,246,0.2)]">
              <UploadCloud className="w-12 h-12 text-violet-400" />
            </div>
            <h3 className="text-xl font-pixel text-white uppercase tracking-widest mb-2">Upload CV-mu</h3>
            <p className="text-zinc-400 font-pixel text-xs uppercase tracking-widest mb-8 max-w-sm">Support PDF, DOCX, dan TXT (maks 5MB)</p>
            
            <div className="flex flex-col items-center gap-4 w-full max-w-md">
              <label className="w-full cursor-pointer">
                <input
                  type="file"
                  accept=".pdf,.docx,.txt"
                  onChange={handleFileChange}
                  className="hidden"
                />
                <div className="w-full text-sm text-zinc-400 bg-violet-500/20 hover:bg-violet-500/30 py-3 px-4 rounded-xl text-center transition border border-violet-500/20 hover:border-violet-500/50 font-pixel tracking-widest uppercase">
                  {selectedFile ? `📄 ${selectedFile.name}` : 'Pilih File CV (PDF, DOCX, TXT)'}
                </div>
              </label>

              {selectedFile && (
                <div className="bg-white/5 rounded-xl p-3 w-full flex items-center justify-between border border-white/5">
                  <span className="text-cyan-400 text-sm font-pixel truncate">📄 {selectedFile.name}</span>
                  <span className="text-zinc-500 text-xs font-pixel">
                    {(selectedFile.size / 1024 / 1024).toFixed(2)} MB
                  </span>
                </div>
              )}

              <Button
                onClick={handleScan}
                disabled={!selectedFile}
                className="w-full h-14 text-md font-pixel tracking-widest uppercase bg-gradient-to-r from-pink-600 to-violet-600 hover:from-pink-500 hover:to-violet-500 text-white shadow-[0_0_20px_rgba(236,72,153,0.4)] transition-all duration-300 rounded-xl border-none disabled:opacity-50"
              >
                <FileText className="w-5 h-5 mr-2" />
                SCAN RESUME (COST: 1 ENR)
              </Button>
            </div>
          </>
        ) : (
          <div className="py-10 flex flex-col items-center space-y-6 w-full">
            <div className="w-20 h-20 border-4 border-pink-500/20 border-t-pink-500 rounded-full animate-spin shadow-[0_0_30px_rgba(236,72,153,0.5)]"></div>
            <div className="text-center w-full max-w-md">
              <h3 className="text-xl font-pixel text-white animate-pulse uppercase tracking-widest">Analyzing CV...</h3>
              <p className="text-violet-400 font-pixel text-xs mt-2 uppercase tracking-widest">Memproses file dan menjalankan AI...</p>
              <div className="w-full bg-zinc-800 rounded-full h-2.5 mt-4 overflow-hidden">
                <div
                  className="bg-gradient-to-r from-pink-500 to-violet-500 h-2.5 rounded-full transition-all duration-500"
                  style={{ width: `${uploadProgress}%` }}
                />
              </div>
              <p className="text-zinc-500 font-pixel text-xs mt-2">{uploadProgress}%</p>
            </div>
          </div>
        )}
      </div>

      {/* HASIL SCAN - PIXEL STYLE */}
      {!isScanning && scanResult && (
        <div className="game-panel border border-violet-500/30 rounded-3xl p-8 w-full max-w-2xl mx-auto space-y-5">
          <div className="flex items-center justify-between">
            <div>
              <h4 className="text-xl font-pixel text-white uppercase tracking-widest">📊 Scan Result</h4>
              <p className="text-sm text-zinc-400 font-pixel">{scanResult.fileName}</p>
            </div>
            <div className="text-4xl font-pixel text-violet-400">
              {scanResult.score}%
            </div>
          </div>

          <div className="w-full bg-zinc-800 rounded-full h-3 overflow-hidden">
            <div
              className={`h-3 rounded-full transition-all duration-700 ${
                scanResult.score >= 80 ? 'bg-green-500' :
                scanResult.score >= 60 ? 'bg-yellow-500' : 'bg-red-500'
              }`}
              style={{ width: `${scanResult.score}%` }}
            />
          </div>

          {scanResult.feedback && scanResult.feedback.length > 0 && (
            <div className="space-y-2 mt-2">
              <p className="text-sm font-pixel text-white uppercase tracking-widest flex items-center gap-2">
                💡 Saran Perbaikan:
              </p>
              <ul className="space-y-1.5">
                {scanResult.feedback.map((item, idx) => (
                  <li key={idx} className="text-sm text-zinc-300 flex items-start gap-2 font-pixel">
                    <span className="text-pink-400 mt-0.5">▸</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <Button
            onClick={downloadReport}
            className="w-full mt-4 font-pixel tracking-widest uppercase bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white shadow-[0_0_20px_rgba(6,182,212,0.3)] transition-all duration-300 rounded-xl border-none"
          >
            <Download className="w-5 h-5 mr-2" />
            Download Full Report (.txt)
          </Button>
        </div>
      )}
    </div>
  );
}